### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by dejankocic** [OfficeDev/Project-Accelerator#20]
Project_for_the_web_Accelerator v1_6_0_18 import fails with the following error message
There are missing dependencies. Install the following solutions before installing this one: "msdyn_ProjectServiceCore (1.0.0.87)".

I tried to follow instructions for updating msdyn_ProjectServiceCore > 1.0.0.87, but the service has already specified version.

What else I could check?

Thx,
Dejan
![import error](https://user-images.githubusercontent.com/6128938/111752600-31635f00-8896-11eb-86bb-a5750b14b64d.png)

[log.txt](https://github.com/OfficeDev/Project-Accelerator/files/6169697/log.txt)

**Comment by matherton-pen** [comment]
I am getting the exact same issue and I can see correct solution it requires is installed and on the correct version as per my screenshot attached. Would be grateful for some help if poss
![image](https://user-images.githubusercontent.com/80957413/111771969-37603c80-88a4-11eb-88ef-2f8cc80a1213.png)

**Comment by matherton-pen** [comment]
I have since solved this problem. I deleted the 3 existing ProjectServiceCore versions and then re-installed via the PowerApps admin section. I was then able to install this solution.  The 3 you are deleting are shown in the screenshot below
![image](https://user-images.githubusercontent.com/80957413/111808006-7c4b9980-88cb-11eb-93e8-009167a21873.png)

**Comment by Vindryn** [comment]
> I have since solved this problem. I deleted the 3 existing ProjectServiceCore versions and then re-installed via the PowerApps admin section. I was then able to install this solution. The 3 you are deleting are shown in the screenshot below
> ![image](https://user-images.githubusercontent.com/80957413/111808006-7c4b9980-88cb-11eb-93e8-009167a21873.png)

Hello,

Thanks for the solution ! How Did you re-installed the 3 "Project" solutions from the PowerApps admin ?

Many Thanks !

**Comment by matherton-pen** [comment]
To re-install, go to https://admin.powerplatform.microsoft.com/environments with the appropriate permissions.  Expand Resources on the left, select Dynamics 365 Apps.

On this page, scroll down to Microsoft Project Service Core and select Install.

The install took about 30mins, and once installed (assuming you uninstalled the 3 previously mentioned), I was then able to import the Project Accelerator solution successfully following that install guide

**Comment by Vindryn** [comment]
> To re-install, go to https://admin.powerplatform.microsoft.com/environments with the appropriate permissions. Expand Resources on the left, select Dynamics 365 Apps.
> 
> On this page, scroll down to Microsoft Project Service Core and select Install.
> 
> The install took about 30mins, and once installed (assuming you uninstalled the 3 previously mentioned), I was then able to import the Project Accelerator solution successfully following that install guide

Many thanks ;)

Best regards

**Comment by matherton-pen** [comment]
One thing to note when you delete all of these, is if you have any content already in Project Online, it will all be deleted! I learnt this the hard way

**Comment by AndrewJNorris** [comment]
> One thing to note when you delete all of these, is if you have any content already in Project Online, it will all be deleted! I learnt this the hard way

Project Online or Project for the Web?
I'd better export them to Excel first if it's P4W.

**Comment by dribblej** [comment]
@matherton-pen . I have a lot of projects in Project for the Web already. If I delete the three solutions and re install them are you saying it will delete all my project data that lives in P4TW?

**Comment by matherton-pen** [comment]
> @matherton-pen . I have a lot of projects in Project for the Web already. If I delete the three solutions and re install them are you saying it will delete all my project data that lives in P4TW?

It wipes the whole thing from what I can see. I learnt the hard way! I dont fully understand how the whole thing hooks together, I think Project sits within Dynamics 365 as an App. Therefore deleting those 3 elements is effectively, in old school terminology, uninstalling the product. Hence the outcome is you lose everything!

That's just my view, but does seem to hook together like that.  The advantage though is that all the new projects you make, do automatically sit within this PowerApp, whereas I dont think you can move existing into this framework (there's a note about that on the main github page from memory)

**Comment by Lindsay-Addie** [comment]
I am currently trying this reinstalling the project service core and now wish I hadn't started this. I don't recommend anyone try this uninstall and reinstall procedure outlined in this thread.

I told PowerApps to uninstall project service core and hope I haven't broken something as there are error messages.

**Comment by dejankocic** [comment]
So, is there a way to overcome the issue?

**Comment by dribblej** [comment]
Can someone who authored this Accelerator patch speak to this. I want to upgrade my orgs project power app that compliments project for the web where we host all our project schedules. I have built it out to include some of the solutions that are part of this patch but I would like to be able to use the OOB entities instead of my custom entities now, along with the new layout, and the newly updated .pbit template. 

I am running into the same issue as outlined about. When I got to upload the solution into the default environment where my project for the web data lives, I am blocked by the error message. This is the txt. log of what is happening. 

`[{"SolutionValidationResultType":"Error","Message":"The following solution cannot be imported: Project_for_the_web_Accelerator. Some dependencies are missing. The missing dependencies are : <MissingDependencies><MissingDependency><Required key=\"183\" type=\"10\" schemaName=\"msdyn_team_msdyn_project_projectteamid\" displayName=\"msdyn_team_msdyn_project_projectteamid\" parentSchemaName=\"team\" parentDisplayName=\"Team\" solution=\"msdyn_ProjectServiceCore (1.0.0.87)\" /><Dependent key=\"183\" type=\"10\" schemaName=\"msdyn_team_msdyn_project_projectteamid\" displayName=\"msdyn_team_msdyn_project_projectteamid\" parentSchemaName=\"team\" parentDisplayName=\"Team\" /></MissingDependency><MissingDependency><Required key=\"183\" type=\"10\" schemaName=\"msdyn_team_msdyn_project_projectteamid\" displayName=\"msdyn_team_msdyn_project_projectteamid\" parentSchemaName=\"team\" parentDisplayName=\"Team\" solution=\"msdyn_ProjectServiceCore (1.0.0.87)\" /><Dependent key=\"331\" type=\"2\" schemaName=\"msdyn_projectteamidyominame\" parentSchemaName=\"msdyn_project\" parentDisplayName=\"Project\" /></MissingDependency><MissingDependency><Required key=\"183\" type=\"10\" schemaName=\"msdyn_team_msdyn_project_projectteamid\" displayName=\"msdyn_team_msdyn_project_projectteamid\" parentSchemaName=\"team\" parentDisplayName=\"Team\" solution=\"msdyn_ProjectServiceCore (1.0.0.87)\" /><Dependent key=\"334\" type=\"2\" schemaName=\"msdyn_projectteamidname\" parentSchemaName=\"msdyn_project\" parentDisplayName=\"Project\" /></MissingDependency></MissingDependencies> , ProductUpdatesOnly : False","ErrorCode":-2147188707,"AdditionalInfo":null}]`

I cannot risk deleting our projects and associated tasks but I want to do this upgrade. Can someone please confirm if deleting the project service core files will delete all my data in my deafult dataverse environment that is tied to the project for the web task schedules on each project. 

Also I am using Project 4 the web, NOT project online.

**Comment by anitobaker** [comment]
@dribblej i am also getting a similar error. you can also try the PowerApps Solution Import Classic Experience and you should see something like this:
![image](https://user-images.githubusercontent.com/82130234/113960177-a3f0aa80-9856-11eb-8d5c-9a8fa61a34f2.png)

Basically it means you are missing the "msdyn_team_msdyn_project_projectteamid" EntityRelationship which is pointing to a "Project Team" lookup field in the Project entity. This is a "managed" field and so we are unable to create this on our own. 

i also also have existing data in my default entity and so deleting the existing Project Service Core solutions is currently not an option

**Comment by BeReasonable** [comment]
Thanks for filing this. We're working on a fix. An updated solution will be available soon.

**Comment by BeReasonable** [comment]
Fixed. Try importing with the latest version of the Accelerator v1_6_0_19

**Comment by dejankocic** [comment]
Hello,

@BeReasonable sorry but the import fails with the latest version too. Please find below the log file.

[log.txt](https://github.com/OfficeDev/Project-Accelerator/files/6295494/log.txt)

**Comment by nicolasmattioni** [comment]
Hello,

Same for me...

`[{"SolutionValidationResultType":"Error","Message":"The following solution cannot be imported: Project_for_the_web_Accelerator. Some dependencies are missing. The missing dependencies are : 
<MissingDependencies>
	<MissingDependency>
		<Required key=\"159\" type=\"10\" schemaName=\"msdyn_team_msdyn_project_projectteamid\" displayName=\"msdyn_team_msdyn_project_projectteamid\" parentSchemaName=\"team\" parentDisplayName=\"Team\" solution=\"msdyn_ProjectServiceCore (1.0.0.87)\" />
		<Dependent key=\"159\" type=\"10\" schemaName=\"msdyn_team_msdyn_project_projectteamid\" displayName=\"msdyn_team_msdyn_project_projectteamid\" parentSchemaName=\"team\" parentDisplayName=\"Team\" /></MissingDependency><MissingDependency>
		<Required key=\"159\" type=\"10\" schemaName=\"msdyn_team_msdyn_project_projectteamid\" displayName=\"msdyn_team_msdyn_project_projectteamid\" parentSchemaName=\"team\" parentDisplayName=\"Team\" solution=\"msdyn_ProjectServiceCore (1.0.0.87)\" />
		<Dependent key=\"309\" type=\"2\" schemaName=\"msdyn_projectteamidyominame\" parentSchemaName=\"msdyn_project\" parentDisplayName=\"Project\" />
	</MissingDependency>
	<MissingDependency>
		<Required key=\"159\" type=\"10\" schemaName=\"msdyn_team_msdyn_project_projectteamid\" displayName=\"msdyn_team_msdyn_project_projectteamid\" parentSchemaName=\"team\" parentDisplayName=\"Team\" solution=\"msdyn_ProjectServiceCore (1.0.0.87)\" />
		<Dependent key=\"313\" type=\"2\" schemaName=\"msdyn_projectteamidname\" parentSchemaName=\"msdyn_project\" parentDisplayName=\"Project\" />
	</MissingDependency>
</MissingDependencies> , 
ProductUpdatesOnly : False","ErrorCode":-2147188707,"AdditionalInfo":null},
{"SolutionValidationResultType":"Warning","Message":"One or more components in the solution already exist in your system as unmanaged components. 
Importing this solution will convert the components into managed components for this solution. 
Warning: Any customizations that your organization has made to these components will be lost. 
After the import operation is complete, managed solutions from other solution publishers will be unable to update these components.","ErrorCode":0,"AdditionalInfo":null}]`

**Comment by AndrewJNorris** [comment]
> Fixed. Try importing with the latest version of the Accelerator v1_6_0_19

I'm afraid not. Like the others, I'm getting the same error as before.
"There are missing dependencies. Install the following solutions before installing this one: "msdyn_ProjectServiceCore (1.0.0.87)"
[log.txt](https://github.com/OfficeDev/Project-Accelerator/files/6296632/log.txt)

**Comment by BeReasonable** [comment]
Reopening, since customers are still having issues. We're taking another look at this.

**Comment by BeReasonable** [comment]
We're working on a test version to address the issue. If you're interested in trying it out, let me know if you can deploy this version. Thank you all for your help, and patience. 
https://github.com/OfficeDev/Project-Accelerator/blob/main/Project_for_the_web_Accelerator%20v1_6_0_22.zip

**Comment by carlosparedesunicomer** [comment]
Hi I tried the version 22, but I got this error message
![error version 22](https://user-images.githubusercontent.com/82618063/114945883-61efd780-9e07-11eb-9857-03afc851b948.png)

**Comment by AndrewJNorris** [comment]
I too get the error when importing v22. Log.xml attached
[Project for the web Accelerator_import.zip](https://github.com/OfficeDev/Project-Accelerator/files/6324561/Project.for.the.web.Accelerator_import.zip)

Solution "Project for the web Accelerator" failed to import: Error while importing Calculated fields name proj_prioritizationscore

**Comment by dribblej** [comment]
![image](https://user-images.githubusercontent.com/34987772/115280332-a972ae00-a0fc-11eb-9cf3-9e7924b4223f.png)

I dont understand why this fails since I have only 5 custom entities, 2 of which I think I would no longer need since Microsoft caught up with what developers were doing before the risks and issues entities were available oob. 

![image](https://user-images.githubusercontent.com/34987772/115280472-d1621180-a0fc-11eb-8f3d-3a04397cec55.png)

I also cannot edit the sitemap. 

The only thing I have done differently from the OOB solution here is added a few custom entities, put them on the site map, embedded my bi report into the power app and created a dataflow from my sales CDS to the my project CDS so account data that is needed from sales is visible for project staff using the P4TW power app in the default org.

**Comment by dribblej** [comment]
Can you publish a solution file that overwrites customizations? At this point, I would be ok with that so it would delete tables I created custom-like Risks and Issues since these entities exist in the solution now. 

I cannot get the solution of update any of my project service core files and even though I only have 5 custom entities, which I am trying to delete some of, the solution will not publish. I just want my team to be able to use this power app without me having to delete all 3 project service core files and risk losing all our existing projects. 

![image](https://user-images.githubusercontent.com/34987772/115794429-d7692400-a382-11eb-8540-e2a1ad0950ce.png)

**Comment by dribblej** [comment]
After doing the most insane search a gutting my customizations I was able to remove the risks entity I created before Microsoft added one to the project service core. I was able to import the solution just fine!

**Comment by BeReasonable** [comment]
Try [this latest build](https://github.com/OfficeDev/Project-Accelerator/blob/main/releases/Project_for_the_web_Accelerator_v1_7_0_3.zip?raw=true) and let me know if you were able to import it successfully.

**Comment by dribblej** [comment]
@BeReasonable Thank you for updating with the recent version. I went ahead and imported it since it was the most recently available solution. Thanks for all of your hard work on this. Appreciate it.

**Comment by dejankocic** [comment]
Hello,

Even it looks the import successfully finishes, I am getting the following error messages on the Solutions pages 

![image](https://user-images.githubusercontent.com/6128938/116365704-cd717600-a805-11eb-848f-180d1d47b56c.png)

**Comment by dejankocic** [comment]
Thx @BeReasonable. Not sure where I can check this.

**Comment by nicolasmattioni** [comment]
> Hi I tried the version 22, but I got this error message
> ![error version 22](https://user-images.githubusercontent.com/82618063/114945883-61efd780-9e07-11eb-9857-03afc851b948.png)

Same for me...

**Comment by nicolasmattioni** [comment]
> @nicolasmattioni, do you have an existing version of the accelerator in that environment? If so, was it deployed as an unmanaged solution?
> 
> Are there any other customizations that have been applied to the tables in the project solution? Can you try removing those customizations and then reimporting the Accelerator?

Yes, we have an old one (v1.4.0.3) installed from the previous package (I guess ?).
Few customizations but not on the data model, only on views and business process flows.

Thanks for you support ! 👍

**Comment by nicolasmattioni** [comment]
> @nicolasmattioni, do you have an existing version of the accelerator in that environment? If so, was it deployed as an unmanaged solution?

To answer your question : Yes, it is flagged as an unmanaged solution.

**Comment by AndrewJNorris** [comment]
I think the problem I've got is layered.
When Project for Web was first set up it went into my Default environment as that was the only option until a few months ago.
Not best practice, I'd prefer it to be in another environment but that wasn't possible. It is now though.

Also, someone else in my org has imported another unmanaged solution (https://oneplan.ai/microsoft-ppm-accelerator-installation-guide/) ModernProjectTemplate_1_4_0_2 and that has left a mess of extra fields/tables in place that are blocking the accelerator import.

I have created a new environment and successfully imported the accelerator into there BUT all my projects are in the Default environment.

I know want to recreate all my projects in the new environment. Anyone know of a way to copy them over?

**Comment by BeReasonable** [comment]
Thanks, @AndrewJNorris and @nicolasmattioni for the updates. 

A package with version 1.4.0.3 is not one we released. From Andrew's notes, it looks like you have deployed customizations via another solution that has blocked the deployment of the Accelerator. You'll need to remove the customizations and then try importing the version of the Accelerator available in this GitHub page.

**Comment by joelarscheid** [comment]
> I think the problem I've got is layered.
> When Project for Web was first set up it went into my Default environment as that was the only option until a few months ago.
> Not best practice, I'd prefer it to be in another environment but that wasn't possible. It is now though.
> 
> Also, someone else in my org has imported another unmanaged solution (https://oneplan.ai/microsoft-ppm-accelerator-installation-guide/) ModernProjectTemplate_1_4_0_2 and that has left a mess of extra fields/tables in place that are blocking the accelerator import.
> 
> I have created a new environment and successfully imported the accelerator into there BUT all my projects are in the Default environment.
> 
> I know want to recreate all my projects in the new environment. Anyone know of a way to copy them over?

If you are looking to migrate projects and data from one Power App environment to another, you might want to visit https://www.pdms.io. PDMS has a utility for migrating Project and Power App data.
