### ISSUE TITLE
Closed projects still appear in the "Active projects" view

### ISSUE THREAD

**Issue by matherton-pen** [OfficeDev/Project-Accelerator#32]
We have marked several projects as Closed in the state and stage fields, however the project still remains Active and is shown within the My Active Projects view.  Is this a bug or something we aren't doing correctly?

Cheers

**Comment by tullisbrian** [comment]
I haven’t checked in our own solution if this would happen but but did you look to see if there are still any open tasks a project for the web for this particular Accelerator record?

**Comment by matherton-pen** [comment]
Good point but I've checked and they are all 100% completed

**Comment by tullisbrian** [comment]
So...I think I replicated your issue. An Accelerator project with state/stage field values all set to "closed", all tasks set to 100% complete, and no issues/risks/changes. Yet, the Project Status ( [statecode] field in Dataverse ) is set = Active. This Active setting seems to be automatic/calculated somehow, but I can't tell calculated from what. I don't have full admin access to things, so it's hard to tell. Some thoughts...

1. Change your views so that you don't use this field at all to consider something active or whatever. Key the filters on state or stage or even % complete for the project.
2. This is a "bug" of some sort...that statecode field that shows as Project Status on various views is not doing what it's supposed to do, whatever that is. When you look at statecode valid values in the Dataverse, they are Active and Inactive. I'd assume that some combination of State = Closed ; Stage = Closed ; % complete based on Tasks = 100% would flip that bit to Inactive.

This might not be the place to opine on this. However, the Accelerator is clearly a "beta" product. And there is zero documentation. In discussions with a Microsoft partner recently, I was asking for the theory of, and data definitions for, these fields and entities - precisely because of this issue you are bringing up. Like, "what do you MEAN by State and State or Project Status = Active? What is a "Manager" versus a "Project Manager" etc and how are those used throughout the flow of the solution from request to project open to close and within various forms, calc fields, views, and reports. I didn't get much in return. So, all in all, this is a neat little product and good raw material for lightweight PPM...but there are some puzzling things here and there and we're going to make do with what we have.

**Comment by BeReasonable** [comment]
Thank you @tullisbrian , for the detailed feedback. Fantastic! 
How are you looking to deploy the Accelerator in your organization? what kinds of changes are you planning on making to it? I'd love to learn more about how you're planning to use it.

The Accelerator does have assumptions baked into it about what customers need. It is meant to essentially cover 80% of what people need. The last 20% are available with the tools available via the Power Platform, as well as via the new API that we have in preview.
https://docs.microsoft.com/en-us/dynamics365/project-operations/project-management/schedule-api-preview

**Comment by tullisbrian** [comment]
@BeReasonable we are looking to deploy the Accelerator as a lightweight PPM layer on top of Project for the Web to support a global IT organization (and potentially other non-IT use cases that need to manage multiple projects - TBD). We expect to be live in May 2021. 

This may or may not be appropriate to post here, and we could move it / take it offline or whatever. But since you asked, I will elaborate!

Extending the Accelerator right now mostly means updates to the Projects table with meaningful Business-specific fields. Other entities may or may not come soon; not sure. The Out of the Box ones will work fine for now.

As you point out, this is a good "80%" fit as-is and we're crafting it to meet our basic needs. We are creating custom fields and changing some existing fields with the right "choices" for us. Updating the forms and views, adapting the BI reports, etc - that's all very straightforward so far. On the reports, for example, we haven't figured out how to provide a deep link that opens a Project for Web task edit within the Accelerator (we can only get a task edit view in Project for the Web); but we're learning as we go. A side benefit for our organization is learning how Model-driven apps work, packaging and updating solutions, the Dataverse, etc.

We are very interested to look at the API. From an end user / task owner perspective, I would love to use the Accelerator to compose a view that shows editable "My tasks" across projects. I would hope that this API gives us an ability to do something like that as all current Task views are read only stubs of what was created in Project for the web.

Speaking of...Project For the Web does not allow a "My tasks" view across projects. Each project is a silo. While I can aggregate tasks in BI and provide hyperlinks to them from the BI report, that seems like a lot of waste and extra clicks. Give me aggregated, editable tasks within the Accelerator. I scratch my head that in 2021 I need to pay a 3rd party for software that integrates and allows me to compose a view that shows me all of my Microsoft-cloud-resident projects and tasks across Azure Devops, Planner/Todo, Project For the Web, Project Online...as a CIO I'm very interested in making peoples' work lives easier. So seeing Accelerator and Project For the Web fit into a coherent Work Management vision is very important to me.

On that note...Accelerator was shown in a 2020 Ignite talk, and barely referred to in the March 2021 Project session at Ignite. How, exactly, does the Accelerator fit into the big picture at Microsoft?

Beyond that, we are excited to see the Project team evolve Project For the Web; we have looked at the roadmap and see a lot of good stuff there. Full usability/feature parity with Planner is a must; for example - checklists and threaded discussions on those tasks within Project for the Web project plans. To the extent that Accelerator and Project for the Web co-evolve, are related or not, will eventually merge into a single offering, I don't know. In any case...we are moving forward and happy to see this year. We will not be shy with future feedback and comments.

**Comment by BeReasonable** [comment]
Hi @tullisbrian, thank you for another detailed reply!

Your feedback about needing a My Tasks experience and Planner parity makes sense. 

In terms of where we're taking the product, we recently hosted a conference where we shared our vision for project management. The sessions were all recorded. You can reach them [here](https://events1.social27.com/reimagine-projectmanagement/).

If you decide to deploy Project into your organization, I'm curious to hear feedback from you about your experience deploying it and from the project managers who use it. Feel free to reach out to my Microsoft email that you'll find in my GitHub profile page.

**Comment by matherton-pen** [comment]
Thanks for the extensive general info, but the issue I've raised at the top is still not resolved. Could you re-open please? I can modify the views, but it seems that this is a bug and having that resolved would be more beneficial than working around it

Cheers

**Comment by BeReasonable** [comment]
@matherton-pen , I'm happy to try changing the behavior. What changes to the views did you make to have them work in a way that you would expect?

**Comment by matherton-pen** [comment]
Could filter My Active Projects so that it hides projects with a state of Closed however the Project Status would still be Active as it currently is for this. So as much as it would hide it from this view, I'm sure this would have unintended consequences.  I would imagine a better solution would be a Flow that automatically executes when the state is marked as Closed, it auto marks the Project Status as Closed, but also a vice versa in case a project re-opens or marked incorrectly. Then I expect everything else would work as intended?

<img width="419" alt="Screenshot 2021-04-29 at 19 31 21" src="https://user-images.githubusercontent.com/80957413/116600950-cf305c00-a921-11eb-9a79-ac0824e88f78.png">

**Comment by tullisbrian** [comment]
For what it's worth the various "Active" views are triggered by this Project Status (statecode in Dataverse). The way to change it to inactive appears to be the standard PowerApps toolbar (which changes the field value that is otherwise inaccessible in any Project edit forms. After setting a project to Inactive, it disappears from the various Active views I've seen. Otherwise...I'm not sure the My Active view helps much. We are likely to just delete the view and define our own version of completed/done/inactive that doesn't use this field at all.

![image](https://user-images.githubusercontent.com/79989987/117209055-79ddca00-adbb-11eb-8d4e-f1ca552503d3.png)

**Comment by BeReasonable** [comment]
It would be good to understand if there's a clear difference between Active and Inactive. For example, having a project with all the work completed isn't enough. Some customizations, such as adding a business process flow may also be involved. 

My recommendation would be to instead define a view that aligns with how your organization defines closed. 

In the future, it also sounds like we should consider adding a business process flow in the Accelerator with an updated set of views for things like Active or Inactive projects.

**Comment by matherton-pen** [comment]
A business process flow to me is the correct way of achieving it, either triggered when project gets to 100% or when the state is changed to Closed.  As a work around I have now changed the My Active Projects view to filter based on Projects with a state not equal to Closed.
