### ISSUE TITLE
Multiple portfolios support

### ISSUE THREAD

**Issue by AndreyKirov777** [OfficeDev/Project-Accelerator#39]
Are there any plans to have multiple portfolio functionality similar to program one?

**Comment by BeReasonable** [comment]
Not currently. If you'd like, you can customize the Accelerator to include a custom Portfolios table and add the UI in the Power App.

**Comment by AndreyKirov777** [comment]
I'm thinking about that. But the question is do I need a dataverse license to create a custom Portfolio table?

**Comment by hmbouk** [comment]
I have been modifying the app with just a Project Plan 3 license.  So far I have added a decision log and lessons learned log along side the current risks, issues, changes and status.

**Comment by matherton-pen** [comment]
@hmbouk I dont suppose its possible to share that somehow? export that solution? I would like to add a decision and lessons learned but if you have already built that would save considerable work

**Comment by hmbouk** [comment]
> @hmbouk I dont suppose its possible to share that somehow? export that solution? I would like to add a decision and lessons learned but if you have already built that would save considerable work

Yes.  I am working on two solutions that layer on top of the base project accelerator.  One solution adds the decision log and lessons learned logs.  The other I am using to modify any drop downs in the project accelerator so that I have drop down values that make sense for my clients. 

I am implementing this with two clients and need to be able to add functionality that I feel is missing but also quickly customize things like business units, departments, etc for each client.  I have also modified the PftW Accelerator report to add report tabs for the decision log and lessons learned.  It is rough and still needs work but am happy to share.  

To be clear, I'm not trying to fork the project accelerator, I have created solutions that add to the solution from this repository.  My changes my conflict with future functionality or maybe not.

**Comment by matherton-pen** [comment]
That sounds good, I'm happy to enhance it etc. but having a start will certainly save duplicate effort

**Comment by BeReasonable** [comment]
It is great to see this kind of collaboration in the community!
@hmbouk, nice use of best practices (additional solution layers) to add scenarios to the Accelerator.

**Comment by hmbouk** [comment]
> It is great to see this kind of collaboration in the community!
> @hmbouk, nice use of best practices (additional solution layers) to add scenarios to the Accelerator.

Any suggestions on the most appropriate way to share my solution and updated PBI report with the community?  Create a repository for my solution(s)?

**Comment by BeReasonable** [comment]
@hmbouk, yes, creating a new GitHub repo and sharing it there is a good approach.
