### ISSUE TITLE
Deploying Power BI template: Reports item: proj_Reports not editable

### ISSUE THREAD

**Issue by martinimarossi** [OfficeDev/Project-Accelerator#46]
Hi

I am following the instruction [https://github.com/OfficeDev/Project-Accelerator](url) to modify the Project Acclerator to use the deployed Power BI template. Herein it is mentioned to click the _Project for the web Accelerator_ solution name to open the solution and after to click _Reports_ item: _proj_Reports_ (type Customization.Type_WebResource).
In my case it is displayed as _Web Resource (HTML)_ and there is no editable field (text editor) to include embed content. 
![proj_Reports_1](https://user-images.githubusercontent.com/92032259/136206100-915c15d3-c2c5-4825-a210-43bb8623d3d9.JPG)
![proj_Reports](https://user-images.githubusercontent.com/92032259/136206192-b9c7a6e7-9241-4275-901e-ce9c1ac735e2.JPG)

**Comment by DanielMonger** [comment]
It appears the new solutions explorer doesn't allow you to edit the managed webresources as before. In the upper right, turn off the Solution preview and you can follow the instructions as normal. 

![image](https://user-images.githubusercontent.com/79956573/136475899-5f272e30-3cee-40b8-9710-d919acee3679.png)


Or you can create a new solution, add the existing 'Reports' Web Resource, then when you click on it you get the option to upload a new file. This mean you need to have a HTML document that contains the code provided (with the updated report url) on you local machine to upload, instead of directly editing in the classic Text editor as shown here.

**Comment by BeReasonable** [comment]
We've updated the instructions for using the Power BI template. Let us know if the directions in the README are unclear, or otherwise don't resolve the issue for you.
